version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: doc-rag-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: doc_rag
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: doc-rag-api
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - MONGODB_URL=mongodb://mongodb:27017/doc_rag
      - MODEL_PATH=/models/current.bin
      - FACT_CACHE_ENABLED=true
      - CACHE_BACKEND=file
      - CACHE_DIR=/cache
      - REDIS_ENABLED=false
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j_password
    volumes:
      - ./models:/models
      - ./uploads:/uploads
      - ./cache:/cache
    depends_on:
      - mongodb
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:5.15-community
    container_name: doc-rag-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/conf:/var/lib/neo4j/conf
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j_password", "MATCH () RETURN count(*) as count"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s