# Qdrant Configuration for Doc-RAG System
service:
  # Network configuration
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  
  # Enable CORS for web interface
  enable_cors: true
  cors_origins: ["*"]

# Storage configuration
storage:
  # Storage directory
  storage_path: /qdrant/storage
  
  # Snapshots configuration  
  snapshots_path: /qdrant/snapshots
  snapshot_recovery: false
  
  # Performance settings
  performance:
    max_search_threads: 4
    max_optimization_threads: 2
    max_indexing_threads: 4
    
  # Memory mapping
  mmap_threshold: 1000000
  
  # Write-ahead log
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0

# Cluster configuration (for distributed setup)
cluster:
  enabled: false
  # node_id: 1
  # p2p:
  #   port: 6335

# Telemetry and logging
telemetry_disabled: false
log_level: INFO

# API and web interface
web_ui: true
service_api_key: null

# TLS configuration (disabled by default)
tls:
  cert: null
  key: null

# JWT configuration for authentication (optional)
# jwt:
#   token: your-jwt-token-here

# Optimizer configuration
optimizer:
  deleted_threshold: 0.2
  vacuum_min_vector_number: 1000
  default_segment_number: 0
  max_segment_size: 20000
  memmap_threshold: 1000
  indexing_threshold: 20000
  flush_interval_sec: 5
  max_optimization_threads: 2

# Collection default configuration
collections:
  default_vector_size: 384
  distance: Cosine
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
    max_indexing_threads: 0
    on_disk: false
  quantization_config:
    scalar:
      type: int8
      always_ram: false
    rescore: true
    oversampling: null

# Recovery configuration
recovery:
  max_recovery_threads: 2